# Generated by Django 4.0.4 on 2022-07-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officesLocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
