# Generated by Django 4.0.4 on 2022-07-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officesLocations', '0002_alter_office_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
