# Generated by Django 4.0.4 on 2022-07-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentprofile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('operation', models.CharField(max_length=255)),
                ('commentaries', models.TextField()),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('proposal_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=255)),
                ('commentaries', models.TextField()),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trail_date', models.DateField()),
                ('commentaries', models.TextField()),
                ('done', models.BooleanField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentprofile.agentprofile')),
            ],
        ),
    ]
