# Generated by Django 4.0.4 on 2022-07-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('activities', '0001_initial'),
        ('officesLocations', '__first__'),
        ('agentprofile', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='propertie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertie'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='agentprofile.agentprofile'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='buyer_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officesLocations.office'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='optioning_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optioning_agent', to='agentprofile.agentprofile'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='propertie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertie'),
        ),
        migrations.AddField(
            model_name='call',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentprofile.agentprofile'),
        ),
        migrations.AddField(
            model_name='call',
            name='propertie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertie'),
        ),
    ]
