# Generated by Django 4.0.4 on 2022-05-13 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=255, null=True, unique=True)),
                ('fname', models.CharField(blank=True, db_column='fname', max_length=30, null=True)),
                ('lname', models.CharField(db_column='lname', max_length=30, null=True)),
                ('homephone', models.CharField(blank=True, db_column='homephone', max_length=15, null=True)),
                ('cellphone', models.CharField(blank=True, db_column='cellphone', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='', regex='^\\+?1?\\d{9,15}$')])),
                ('office', models.CharField(choices=[(0, 'RE/MAX México')], default=0, max_length=20)),
                ('origin', models.CharField(choices=[(0, 'SIR || Tarjeta Digital')], default=0, max_length=20)),
                ('agent', models.CharField(choices=[(0, 'Dinorah Felgueres Hernández'), (1, 'Eduardo Cruz García'), (2, 'Felipe Gonzalez Rosales'), (3, 'Salvador Haro Cisneros')], default=0, max_length=20)),
                ('status', models.CharField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=False, max_length=20)),
                ('typeof', models.CharField(choices=[(0, 'Tipo 1'), (1, 'Tipo 2')], default=0, max_length=20)),
                ('notes', models.TextField()),
            ],
        ),
    ]
